### ISSUE TITLE
pwru loongarch support?

### ISSUE THREAD

**Issue by vincentmli** [cilium/pwru#559]
It appears pwru support loongarch, but when I build pwru on loongarch64 platform, I got:

```
[root@fedora pwru]# TARGET_GOARCH=loong64 GOARCH=loong64 make pwru
TARGET_GOARCH=loong64 go generate
Generating for loong64
/home/loongarch/pwru/bpf/kprobe_pwru.c:777:2: error: Unsupported architecture
  777 | #error Unsupported architecture
      |  ^
/home/loongarch/pwru/bpf/kprobe_pwru.c:823:14: error: use of undeclared identifier 'ip_offset'; did you mean 'Opt_offset'?
  823 |         return ip - ip_offset;
      |                     ^~~~~~~~~
      |                     Opt_offset
./bpf/headers/vmlinux-loongarch.h:104374:2: note: 'Opt_offset' declared here
 104374 |         Opt_offset = 7,
        |         ^
2 errors generated.
Error: compile: exit status 1
exit status 1
build.go:5: running "go": exit status 1
make: *** [Makefile:21: pwru] Error 1

```

@chenhengqi maybe `bpf/kprobe_pwru.c` need loongarch addition for `ip_offset` ?

```
766 static __always_inline u64
767 get_func_ip(void) {
768         u64 fp_tramp, ip;
769 
770 #if defined(bpf_target_x86)
771         static const int ip_offset = 5/* sizeof callq insn */;
772         u64 fp;
773 #elif defined(bpf_target_arm64)
774         /* Ref: commit b2ad54e1533e ("bpf, arm64: Implement bpf_arch_text_poke() for arm64") */
775         static const int ip_offset = 12/* sizeof 3 insns */;
776 #else
777 #error Unsupported architecture
778 #endif
```

**Comment by Asphaltt** [comment]
It was caused by PR #468, which introduced a bunch of function IP enhancements for x86_64 and arm64, excluding loongarch.

**Comment by vincentmli** [comment]
> It was caused by PR [#468](https://github.com/cilium/pwru/pull/468), which introduced a bunch of function IP enhancements for x86_64 and arm64, excluding loongarch.

@Asphaltt I guess you have fix for loongarch then?  hengqi says he may look at it too.

**Comment by Asphaltt** [comment]
> I guess you have fix for loongarch then? 

Sorry, I'm unable to fix it, because I do not have loongarch device to test it. I'm unfamiliar with bpf on loongarch meanwhile.

Let us wait for good news from @chenhengqi .

**Comment by vincentmli** [comment]
@chenhengqi @Asphaltt hengqi suggested below diff, Leon, any idea?

```
[root@fedora pwru]# git diff
diff --git a/bpf/kprobe_pwru.c b/bpf/kprobe_pwru.c
index c0b049b..e5a352f 100644
--- a/bpf/kprobe_pwru.c
+++ b/bpf/kprobe_pwru.c
@@ -773,6 +773,8 @@ get_func_ip(void) {
 #elif defined(bpf_target_arm64)
        /* Ref: commit b2ad54e1533e ("bpf, arm64: Implement bpf_arch_text_poke() for arm64") */
        static const int ip_offset = 12/* sizeof 3 insns */;
+#elif defined(bpf_target_loongarch)
+       static const int ip_offset = 0;
 #else
 #error Unsupported architecture
 #endif
[root@fedora pwru]# 
[root@fedora pwru]# 
[root@fedora pwru]# 
[root@fedora pwru]# 
[root@fedora pwru]# 
[root@fedora pwru]# TARGET_GOARCH=loong64 GOARCH=loong64 make pwru
TARGET_GOARCH=loong64 go generate
Generating for loong64
CC=cc GOARCH=loong64 CGO_ENABLED=1 go build  \
	-ldflags "-w -s \
	-X 'github.com/cilium/pwru/internal/pwru.Version=v1.0.10-pre-85-g8f322d2'"
# github.com/leonhwangprojects/bice
vendor/github.com/leonhwangprojects/bice/compile.go:242:22: undefined: h2ns
vendor/github.com/leonhwangprojects/bice/compile.go:251:22: undefined: h2nl
vendor/github.com/leonhwangprojects/bice/compile.go:261:15: undefined: h2nll
make: *** [Makefile:22: pwru] Error 1
```

**Comment by Asphaltt** [comment]
> +#elif defined(bpf_target_loongarch)

There are two places (the latter one can be rewrote as `fp_tramp = get_tramp_fp()`) to get the FP of trampoline according to `if defined(bpf_target_XXX`. So do `loong64`.

**Comment by brb** [comment]
Fixed by https://github.com/cilium/pwru/commit/920c78a8556020543245a03dbe5ecbdce331920c.
